### ISSUE TITLE
感谢大佬的项目，有个问题请教一下

### ISSUE THREAD

**Issue by BaeKey** [DDS-Derek/EasyImage#2]
先说问题，我不知道怎么配置SSL

我在网上看到的方案是反向代理，但是docker镜像里面本来不就是nginx+php吗，我想把docker里面的配置文件直接映射出来配置ssl，但是这个镜像和参考的那个nginx+php7一样，我折腾了一下午，在容器里面没搞明白默认的配置在哪里。使用nginx -t查看过了，没看到80端口的配置。

接着我尝试自己用php镜像+nginx镜像搭建，遇到了权限755，安装时后台报错权限被拒绝，同时浏览器访问的链接算是127.0.0.1开头，一下午没有搞明白问题在哪里，但是同样的环境配置typecho一切正常。

所以想请教一下这个docker镜像的nginx如何正确映射出来。

**Comment by BaeKey** [comment]
不好意思我的问题，下午没看到 unix:/var/run/php-fpm.sock，只看到9000那句被注释了，已经解决了
这样映射就可以了
```
version: '3.3'
services:
  easyimage:
    image: ddsderek/easyimage:latest
    container_name: easyimage
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./easyimages/config:/app/web/config
      - ./easyimages/i:/app/web/i
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
```
